spring:
  application:
    name: cadastro-servicos
  datasource:
    url: jdbc:h2:mem:servicesdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true  # Permitir acesso à console H2

  jpa:
    hibernate:
      ddl-auto: update  # Atualizar automaticamente o schema do banco de dados
    show-sql: true  # Exibir as queries SQL no console